version: '3'
services:
  app:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/project
     - /dev:/dev
     - /dev/gpiomem:/dev/gpiomem
     - /sys:/sys
     - /etc/udev/rules.d:/etc/udev/rules.d
    devices:
     - /dev:/dev
    group_add:
      - 998
      - 997
    privileged: true
    environment:
      GPIO_GID: 997

